### ISSUE TITLE
Make it mobile-friendly

### ISSUE THREAD

**Issue by gaearon** [KyleAMathews/react-headroom#1]
There perhaps should be a prop like `disabled` so users may set it to `false` based on media query or touch support. Sorry if it's there and I didn't notice.

**Comment by KyleAMathews** [comment]
There wasn't — thanks for the suggestion! Published a 1.2.0 with addition.

**Comment by champeng** [comment]
@gaearon @KyleAMathews Didn't get how can we control the disable prop using media query, though.

**Comment by oyeanuj** [comment]
@KyleAMathews I wonder if a more robust way might be to offer a `disableOnMobile` option. Otherwise, I imagine every user would need to roll their own check for mobile to disable it as per above comment?

**Comment by KyleAMathews** [comment]
PRs accepted :-)
