### ISSUE TITLE
Inline height not recalculated on resize

### ISSUE THREAD

**Issue by rafaelderolez** [KyleAMathews/react-headroom#100]
React-headroom seems to force an inline style height on the `headroom-wrapper` even though `disableInlineStyles` is set to true. I'd be fine with this if the height would recalculate when resizing, but it doesn't.

The [official version](http://wicky.nillia.ms/headroom.js/) of headroom doesn't seem to do this on the demo site.

**Comment by rafaelderolez** [comment]
After some more testing I see that `headroom-wrapper` gets an inline height to prevent the content underneath from jumping while switching from unfixed to unpinned.

Regardless, it would be nice it headroom recalculated its height.

**Comment by JLongley** [comment]
+1

Looking at it, it does resize the header in the componentDidUpdate() function.

My use case is a collapsing menu on mobile.  When they hit the collapse button, the header shrinks.  

The problem I'm facing is that componentDidUpdate remeasures the header instantaneously, and doesn't give it time for the animation to finish.  If I call this.forceUpdate() on a timeout, the header janks back to the correct size.

**Comment by rafaelderolez** [comment]
@JLongley componentDidUpdate only sets a new height according to the following: `// If children have changed, remeasure height.`

I'm not changing any children for my responsive styles. I only update some padding and font-sizes, which obviously changes the height of my header and subsequently would have to set a new height on headroom.

**Comment by rusi** [comment]
@JLongley I am having the exact same issue. Were you able to find a good solution to this problem?

**Comment by rafaelderolez** [comment]
@rusi Here's my temporary fix:

When resizing the window, I execute `setHeaderHeight` which gets the height of my actual header element. I put it in the state of my component and then pass that in Headroom's `wrapperStyle` prop. Hope that works for you! (You can probably debounce this to improve performance, but here's a very barebones version.)

```
componentDidMount() {
  this.setHeaderHeight.bind(this);
  window.addEventListener('resize', this.setHeaderHeight.bind(this));
}

setHeaderHeight() {
  const headerHeight = this.header.clientHeight;
  this.setState({ headerHeight });
}

render() {
    const { headerHeight } = this.state;

    return (
      <Headroom
        disableInlineStyles
        wrapperStyle={headerHeight}
      >
        <header ref={(ref) => { this.header = ref; }}>
        …
        </header>
      </Headroom>
  );
}
```

@KyleAMathews What do you think?

**Comment by emilbruckner** [comment]
+1
