### ISSUE TITLE
Plugin "transform-undefined-to-void" messing up 

### ISSUE THREAD

**Issue by ruxiang05** [KyleAMathews/react-headroom#101]
<img width="354" alt="screen shot 2017-03-04 at 1 00 08 pm" src="https://cloud.githubusercontent.com/assets/14987594/23578973/c8dda5d6-00da-11e7-9cba-f668caa43c44.png">

Some guidance would be very helpful as it happens as soon as I render the app.

**Comment by KyleAMathews** [comment]
Generally you shouldn't be compiling code in node_modules. We compile this
module to es5 when we publish it to npm.

**Comment by ruxiang05** [comment]
I am not compiling anything from node_modules. I added the package to my react native app and run the app. That's it. Did nothing else than that.

**Comment by KyleAMathews** [comment]
transform-undefined-to-void is a bable plugin. Also this module is just for
the web and won't work on react native without rewriting the web specific
parts.

**Comment by ruxiang05** [comment]
Ohhh, I didn't realise this. Thank you for your answers!
