### ISSUE TITLE
How use it if i want to stick my footer ?

### ISSUE THREAD

**Issue by ihsansatriawan** [KyleAMathews/react-headroom#103]
How can i use it for my footer not my header ? it is possible ?

thx

**Comment by schalkventer** [comment]
@ihsansatriawan Did you ever get an answer? I wondering the same thing.

**Comment by fraudfilter** [comment]
> @ihsansatriawan Did you ever get an answer? I wondering the same thing.

Set `disableInlineStyles` prop to true

` 
 <Headroom disableInlineStyles={true}>                                                                             
   <h1>You can put anything you'd like inside the Headroom Component</h1>                                          
</Headroom> 
`

Then put in your styles

`.headroom {
  bottom: 0;
  left: 0;
  right: 0;
  zIndex: 1;
}
.headroom--unfixed {
  position: relative;
  transform: translateY(0);
}
.headroom--scrolled {
  transition: transform 200ms ease-in-out;
}
.headroom--unpinned {
  position: fixed;
  transform: translateY(100%);
}
.headroom--pinned {
  position: fixed;
  transform: translateY(0%);
}` 

More customization look at https://kyleamathews.github.io/react-headroom/

**Comment by vinaysharma14** [comment]
Hi, @fraudfilter .

What should be the hierarchy in JSX for using Headroom?
`
<Headroom />
<PageContent />
`
or
`
<Headroom />
<PageContent />
`

**Comment by vinaysharma14** [comment]
Hi, @fraudfilter . When I scroll immediately to the top, footer disappears.
