### ISSUE TITLE
should remove scroll listener(s) when unmounting

### ISSUE THREAD

**Issue by WickyNilliams** [KyleAMathews/react-headroom#11]
Scroll event listeners aren't cleaned up on unmounting. On a multipage app, where Headroom is used only on some pages, you get errors after it's been unmounted because you're attempting to alter state on a component that is no longer in the DOM.

(note the irony that I'm using your headroom component haha)

**Comment by KyleAMathews** [comment]
Haha, no you using this is Awesome! As it means you'll bring your trained headroom eye to fixing up remaining bugs like this :)

Fixed and published 1.6.2

**Comment by WickyNilliams** [comment]
Thanks for the quick fix! Will test today and let you know if there are any issues.

A rising tide lifts all boats, as they say. This is the second time in a week I've been contributing to "competing" projects :)
