### ISSUE TITLE
React Headroom doesn't work with React 0.14-rc1

### ISSUE THREAD

**Issue by mik01aj** [KyleAMathews/react-headroom#12]
It fails with these exceptions:

![screenshot 2015-10-07 12 35 50](https://cloud.githubusercontent.com/assets/3027415/10335292/f54018be-6cef-11e5-8f85-bd988601126b.png)

The errors saying `Uncaught TypeError: Cannot read property 'props' of undefined` have a stacktrace that starts in `Headroom.handleScroll`.

**Comment by KyleAMathews** [comment]
I'm guessing this is an error in your application. I'm using Headroom on a project and it's working just fine. That "style object has been previously mutated" warning does need fixed.
