### ISSUE TITLE
react-footroom?

### ISSUE THREAD

**Issue by TheFastCat** [KyleAMathews/react-headroom#139]
Hello I love this functionality for my header and want the same for my footer which is currently forever-floating at the bottom of the page during a scroll. Is it possible to configure react-headroom to do it's thing at the bottom of a page instead of the top?

**Comment by vinaypuppal** [comment]
@TheFastCat Checkout https://github.com/ratson/react-grounding

**Comment by S1nPur1ty** [comment]
@vinaypuppal doesn't seem to work properly. I tried it with a clean div component, but seems very buggy so far.
