### ISSUE TITLE
Do we really need lodash?

### ISSUE THREAD

**Issue by erykpiast** [KyleAMathews/react-headroom#148]
Multiple lodash libraries (dependencies of `shallowequal`) take almost 50% of the bundle according to https://bundlephobia.com/result?p=react-headroom@2.2.2. Would you welcome a PR getting rid of this dependency?

**Comment by endymion1818** [comment]
I don't think lodash is a dependency, take a look here: https://github.com/dashed/shallowequal/blob/master/package.json
