### ISSUE TITLE
StrictMode compliancy

### ISSUE THREAD

**Issue by mdugue** [KyleAMathews/react-headroom#157]
Hey, thanks a lot for this great library. I'm a hughe fan and really enjoy using it in many projects.
Lately I found out, that react-headroom is not compliant with react **strict mode**. Is there work in progress towards this? I might provide a PR if you are intereseted, but I have seen, that some PRs are open without reaction since quite a while.

**Comment by janczizikow** [comment]
A bit late for the party here, but this was fixed in #168. In case someone is still experiencing warnings about react-headroom in react strict mode, just update react-headroom to >= 3.0.0.
