### ISSUE TITLE
Usage of componentWillReceiveProps 

### ISSUE THREAD

**Issue by JLeggatt** [KyleAMathews/react-headroom#167]
Since the latest update to React devtools. I've noticed the following warning:

> Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.
> 
> * Move data fetching code or side effects to componentDidUpdate.
> * If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
> * Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
> 
> Please update the following components: Headroom

Are there any plans to refactor away from this?

**Comment by vjs3** [comment]
Hey! @KyleAMathews @endymion1818 any updates on this issue?

**Comment by endymion1818** [comment]
Yep, this is something that really needs to be done. I don't get much time to code my own projects these days unfortunately. I don't suppose you'd like to take a look at it?

**Comment by vjs3** [comment]
Hey, @endymion1818. Sorry for my late response, I just saw your comment. I see that @janczizikow has already raised a pull request and it seems that it will fix the problem :)
