### ISSUE TITLE
Glitch in safari mobile

### ISSUE THREAD

**Issue by mhedengren** [KyleAMathews/react-headroom#185]
I saw that this was an issue back in 2018-2019 but the exact same issue is happing for me now (using gatsby).

The issue back then https://github.com/KyleAMathews/react-headroom/issues/154 

Is anyone else experiencing this?

**Comment by rajinwonderland** [comment]
Having the same issue

**Comment by olerichter00** [comment]
I'm experiencing the same 👍

**Comment by janczizikow** [comment]
@olerichter00 would it be possible to share a link to a repo that reproduces this?

**Comment by olerichter00** [comment]
@janczizikow sure, you can reproduce it with this repo: https://github.com/olerichter00/h4ckernews

I could reproduce the glitches with Safari on MacOS (iOS, Chrome and Firefox seem to work as expected).

**Comment by olerichter00** [comment]
Delaying the state change to `unfixed` with `setTimout()` seems to prevent the glitches (https://github.com/KyleAMathews/react-headroom/pull/194). Although the header still disappears for a few milliseconds when scrolling to the top fastly.

Related Commit, that apparently introduced the Glitch in 2018: https://github.com/KyleAMathews/react-headroom/commit/c56d15fbd0087b211394eca435f7cfaa4c1bfcf2

**Comment by endymion1818** [comment]
Hi @olerichter00 please could you confirm if the latest release fixes the issue for you?

**Comment by olerichter00** [comment]
> Hi @olerichter00 please could you confirm if the latest release fixes the issue for you?

Yes, the latest release fixed the issue for me!

**Comment by endymion1818** [comment]
Cool!

**Comment by endymion1818** [comment]
Closing in favor of #195 because sadly the issue is recurring for some users.
