### ISSUE TITLE
Support other elements being source for scroll events

### ISSUE THREAD

**Issue by WickyNilliams** [KyleAMathews/react-headroom#34]
Sometimes you want to get scroll events from sources other than `window` e.g. an element with overflow. 

Not sure how this would actually work in the react world. In the original headroom you just pass a ref to the element you want to listen to scroll events on when constructing the instance. Not as easy with react where you'd have to wait for the scroll source component to be mounted first.

Worth consideration anyway :)

**Comment by KyleAMathews** [comment]
@borisnadion has an almost merged PR for this actually @ https://github.com/KyleAMathews/react-headroom/pull/10

**Comment by KyleAMathews** [comment]
Merged #10
