### ISSUE TITLE
Support for bottom navigation

### ISSUE THREAD

**Issue by krisfields** [KyleAMathews/react-headroom#36]
I'm trying to accomplish what Medium does, where they have disappearing navigation both at the top and bottom at the same time. 

Example: https://medium.com/life-learning/how-to-work-40-hours-in-16-7-the-simple-technique-that-gave-me-my-life-back-8f98ec011862#.mp835i8jf

Is this possible with react-headroom?  I haven't had any luck so far.  When I try, the bottom navigation never disappears, and when scrolling it is 25px above the bottom of the window.

Thanks.

**Comment by krisfields** [comment]
I figured it out. 

I just needed to add disableInlineStyles="true" and then add the following css:
.headroom {
  transition: transform 200ms linear;
  position: fixed;
  left: 0;
  right: 0;
  bottom: -50px; /* equal to height of footer */
  zIndex: 1;
}
.headroom--pinned {
  transform: translateY(-100%);
}
.headroom--unpinned {
  transform: translateY(0%);
}

So basically I just needed to set bottom instead of top, and then flip the translates.

**Comment by vinaysharma14** [comment]
Hi, @krisfields  . When I scroll immediately to the top, footer disappears.
