### ISSUE TITLE
feature: add "fixed" prop so can set to always be on

### ISSUE THREAD

**Issue by KyleAMathews** [KyleAMathews/react-headroom#4]
though this would be an odd name as only `fixed=true` makes sense as there's already a `disable` prop.

Or perhaps name it `alwaysFixed`...

**Comment by celiofonseca** [comment]
+1

**Comment by jasonadt** [comment]
+1

**Comment by KyleAMathews** [comment]
PRs accepted :-)

**Comment by stefensuhat** [comment]
is this merge?

**Comment by henit** [comment]
+1 When is the pin property going to be merged

**Comment by Polcius** [comment]
This component in general seems a bit abandoned. There are many bugs open and pull requests pending. @KyleAMathews are you there? :)

**Comment by janczizikow** [comment]
added in #205
