### ISSUE TITLE
initialState className

### ISSUE THREAD

**Issue by PHaroZ** [KyleAMathews/react-headroom#45]
Hi,

First, thanks for your job, it's pretty cool :)

After reading src code I see that when ```state``` change to "unfixed" ```className``` is set to "headroom--unfixed", which is pretty cool for custom styling.
However in ```getInitialState``` ```state``` is to "unfixed" but ```className``` is to "headroom--pinned", this seems to be an issue and makes useless the "headroom--unfixed" class.

**Comment by tzvigqb** [comment]
I agree with @PHaroZ on this. In my case, since we start out with "headroom--pinned", I can't do custom styling for the initial state. It has to be the same as when unpinned, which does not work for me.

**Comment by KyleAMathews** [comment]
I'd accept a PR for this and #43 (which seems a very similar problem).

**Comment by KyleAMathews** [comment]
Fixed in 2.0.0 https://github.com/KyleAMathews/react-headroom/releases/tag/v2.0.0
