### ISSUE TITLE
React.__spread warning in React 15

### ISSUE THREAD

**Issue by thangngoc89** [KyleAMathews/react-headroom#57]
I know this is not an issue with react-headroom but an issue with coffee-react-transform. This is the only blocker that prevent me from using React 15. Do you have any plan to fix this ? I'd be happy to send a PR to convert this the codebase to ES6 and JSX.

**Comment by KyleAMathews** [comment]
Converting to ES6 would be great! If you do so, please copy the `.eslintrc` from Gatsby https://github.com/gatsbyjs/gatsby/blob/master/.eslintrc (minus the Ava plugin + __PREFIX_LINKS__ global).

**Comment by thangngoc89** [comment]
@KyleAMathews what do you think about ES6 class for React component ? PureRendereMixin can be easily replaced

**Comment by KyleAMathews** [comment]
👍 to ES6 classes.

**Comment by thangngoc89** [comment]
Fixed in #59
