### ISSUE TITLE
Add class name to wrapper div

### ISSUE THREAD

**Issue by cleercode** [KyleAMathews/react-headroom#7]
I need to style the wrapper `div` to avoid some weird `z-index` issues.

**Comment by KyleAMathews** [comment]
I'll add this soon but in the meantime you can use the wrapperStyle prop
which I forgot to document
https://github.com/KyleAMathews/react-headroom/commit/9d98a982200b1f9b95f27ec724e14f7401770bf4

**Comment by KyleAMathews** [comment]
Commited change in a0f17e1 and published a 1.5.0
