### ISSUE TITLE
Headroom example on github pages seems broken

### ISSUE THREAD

**Issue by amrit92** [KyleAMathews/react-headroom#82]
https://kyleamathews.github.io/react-headroom/

Doesn't seem to work on Chrome

**Comment by KyleAMathews** [comment]
hrmmm... thanks, looking into this.

**Comment by KyleAMathews** [comment]
Ok, should be fixed. Looks like Gatsby 0.11.1 had a regression which affected this site.

**Comment by amrit92** [comment]
Thanks @KyleAMathews
