### ISSUE TITLE
iOS Safari & desktop scroll bouncing is triggering the header

### ISSUE THREAD

**Issue by barodeur** [KyleAMathews/react-headroom#89]
At the bottom of a page, when I continue to scroll down after I reach the bottom of the page, and release the scroll, it automatically scrolls up to the bottom of the page.
This automatic scroll pin the header.

Having an option to show the header when the scroll reach the end of the page could be useful, I think https://github.com/WickyNilliams/headroom.js has one and it's possible to opt out.

The scroll bouncing of chrome on desktop does not trigger the header.

**Comment by barodeur** [comment]
I'm working on this and I'll send a pull request soon.

**Comment by KyleAMathews** [comment]
Fixed by #90
