### ISSUE TITLE
Use PureComponent over PureRenderMixin

### ISSUE THREAD

**Issue by bebraw** [KyleAMathews/react-headroom#95]
React 15.3.0 introduced `PureComponent`. The cool thing is that `preact-compat` supports that too now. So refactoring react-headroom to use that would get something that works with Preact as well.

**Comment by KyleAMathews** [comment]
This would work well but I don't want to require > React 15.3 just yet.

How about just implementing `shouldComponentUpdate` directly? Preact core supports that. Just do the same shallow compare `PureComponent` does.

**Comment by bebraw** [comment]
Yeah, that would work.

**Comment by KyleAMathews** [comment]
Perhaps just use the npm module shallowcompare as in the code snippet?

**Comment by bebraw** [comment]
Yeah, let's go with that. Good enough.
